### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Daggerbot** [Daggerbot/aurum#1]
Version 0.3.0

* [ ] Implement PNG codec for dimage.
* [ ] Create dterm, a tcod-like terminal window library for Roguelike game development, fully functional under \*nix/X11.

Version 0.4.0

* [ ] Port dwindow and dgl (and thus dterm) to Windows.

Eventually

* [ ] Port dwindow and dgl to macOS.
* [ ] Implement JPEG codec for dimage.
* [ ] Add Wayland support, choosable at runtime, to \*nix port of dwindow.
* [ ] Add EGL / OpenGL ES support to dgl.
* [ ] Create axis, a desktop application GUI library.
* [ ] Create daudio, an audio playback and I/O library.
* [ ] Create ddialog, a library for native dialogs (file, font, color, etc.) under all supported platforms.
* [ ] Add raw input support as a default cargo feature to dinput.
* [ ] Add full screen mode for dwindow.
* [ ] Add `View`s (subwindows) for dwindow.
* [ ] Add icon and cursor manipulation for dwindow.

Future Maybes

* [ ] Add `Pixmap`s (offscreen surfaces) for dwindow and a library for native 2D drawing (GDI, Xrender, Quartz 2D).
* [ ] Add support for other rendering APIs (Vulkan, Direct3D, Metal).
* [ ] Port dwindow and dgl to Android and iOS.
* [ ] Port dwindow and dgl to emscripten and WebGL.
